#!/usr/bin/env bash

template_project.gitsubmodules() {
  git submodule init && git submodule update
}

template_project.build() {
  mkdir build && cd build && cmake .. && make && make install
}

main() {
  template_project.gitsubmodules
  template_project.build
}

(( $_s_ )) || main
